In [ ]:
import torch

In [ ]:
# !pip install torch

In [ ]:
torch.__version__

'2.4.0+cu121'

In [ ]:
l = [1, 2, 3]
t1 = torch.tensor(l)
t1

tensor([1, 2, 3])

In [ ]:
type(t1)

torch.Tensor

In [ ]:
import numpy as np

In [ ]:
np_array = np.array([1, 2, 3])
t2 = torch.tensor(np_array)
t2

tensor([1, 2, 3])

In [ ]:
t1 = torch.ones((2, 2))
t1

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
t2 = torch.zeros((2, 2))
t2

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
torch.manual_seed(30)
t3 = torch.rand((2, 2))
t3

tensor([[0.9007, 0.7464],
        [0.4716, 0.8738]])

In [ ]:
t4 = torch.randint(0, 10, size = (2, 2))
t4


tensor([[7, 7],
        [5, 6]])

In [ ]:
t5 = torch.arange(0, 10, 3)
t5

tensor([0, 3, 6, 9])

In [ ]:
t5 = torch.arange(0, 9).reshape(3, 3)
t5

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [ ]:
t10 = torch.ones_like(t5)
t10

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [ ]:
# tensor attributes

# t.shape
# t.ndim
# t.dtype
# t.device

In [ ]:
t1 = torch.tensor(4)
t2 = torch.tensor([1, 2, 3])
t3 = torch.tensor([[1, 2, 3], [1, 2, 3]])
t4 = torch.tensor([[[1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3]]])

print(t1.ndim, t2.ndim, t3.ndim, t4.ndim)
print(t1.shape, t2.shape, t3.shape, t4.shape)

0 1 2 3
torch.Size([]) torch.Size([3]) torch.Size([2, 3]) torch.Size([2, 2, 3])


In [ ]:
# dtype

# torch.float32 (torch.float)
# torch.float64 (torch.double)
# torch.int32
# torch.int64
# torch.uint8


In [ ]:
t1 = torch.tensor([1, 2, 3])
t1.dtype

torch.int64

In [ ]:
t1 = torch.tensor([1.0, 2.0, 3.0])
t1.dtype

torch.float32

In [ ]:
t1 = torch.tensor([1.0, 2, 3])
t1.dtype

torch.float32

In [ ]:
t1

tensor([1., 2., 3.])

In [ ]:
import torch
t1 = torch.tensor([1, 2, 3], dtype = torch.float32)
t1.dtype

torch.float32

In [ ]:
t2 = torch.tensor([1, 2, 3], dtype = torch.float32, requires_grad = True)

In [ ]:
# t.device

t1.device

device(type='cpu')

In [ ]:
torch.cuda.is_available()

True

In [ ]:
cuda_tensor = torch.tensor([1.0, 2.0, 3.0], device = 'cuda')

In [ ]:
cuda_tensor.device

device(type='cuda', index=0)

In [ ]:
cuda_tensor = cuda_tensor.to('cpu')

In [ ]:
cuda_tensor.device

device(type='cpu')

In [ ]:
t1 = t1.to('cuda')

In [ ]:
t1.device

device(type='cuda', index=0)

In [ ]:
torch.cuda.device_count()

1

In [ ]:
torch.cuda.get_device_name(0)

'Tesla T4'

In [ ]:
# accessing elements

t = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
t.ndim

3

In [ ]:
t[0][0][0]

tensor(1)

In [ ]:
t[0][0]

tensor(1)

In [ ]:
t[0, 0]

tensor(1)

In [ ]:
t[:2]

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
t[:, -1]

tensor([3, 6, 9])

In [ ]:
t[1, 1:]

tensor([5, 6])

In [ ]:
t = torch.tensor([1, 2, 3, 4, 6])
t[t > 3]

tensor([4, 6])

In [ ]:
# standard function

# torch.sum()
t

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
# t1.sum()
torch.sum(t1, dim = 1)


tensor([ 6, 15])

In [ ]:
torch.max(t1, dim = 1)

torch.return_types.max(
values=tensor([3, 6]),
indices=tensor([2, 2]))

In [ ]:
# torch.mul()

a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# torch.mul(a, b)

a * b



tensor([ 4, 10, 18])

In [ ]:
# torch.matmul()
# @

a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[1, 2], [3, 4]])

# torch.matmul(a, b)
a@b

tensor([[ 7, 10],
        [15, 22]])

In [ ]:
b.T

tensor([[1, 3],
        [2, 4]])

In [ ]:
torch.save(a, 'tensor_a.pt')

In [ ]:
t2 = torch.load('tensor_a.pt')

<ipython-input-54-50aa6070bf25>:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  t2 = torch.load('tensor_a.pt')


In [ ]:
t2

tensor([[1, 2],
        [3, 4]])

In [ ]:
t2 = torch.tensor([[1.0, 2], [3, 4]])

In [ ]:
t1 = torch.tensor([[1.00001, 2.00001], [3.00001, 4.00001]])
torch.allclose(t1, t2, atol= 1e-4)

True

In [ ]:
t = torch.linspace(-5, 5, 10)

In [ ]:
# t2 = torch.clone(t1)
# t2 = t1.clone()

In [ ]:
x = torch.tensor(2.0, requires_grad = True)
y = torch.tensor(3.0, requires_grad = False)
z = 3*x**2 + 4*y**2
z.backward()
print(x.grad)
print(y.grad)



tensor(12.)
None


In [ ]:
x = torch.tensor(2, requires_grad = False)
w = torch.tensor(3., requires_grad = True)
b = torch.tensor(1., requires_grad = True)

y = w * x + b

y.backward()

print(x.grad)
print(w.grad)
print(b.grad)

None
tensor(2.)
tensor(1.)


In [ ]:
x.requires_grad

False

In [ ]:
x = torch.ones(2, 2)
x

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
x = torch.ones(2, 2, requires_grad = True)
y = x + 2
z = y * y * 3
out = z.mean()

out.backward()

print(x.grad)
print(y.grad)
print(z.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
None
None


<ipython-input-76-1bbd30734c52>:9: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:489.)
  print(y.grad)
<ipython-input-76-1bbd30734c52>:10: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more in

In [ ]:
# leaf tensors
a = torch.rand(2, 2, requires_grad = True)
b = a + 2
c = torch.rand(2, 2, requires_grad = False)
d = c + 2

print(a.is_leaf)
print(b.is_leaf)
print(c.is_leaf)
print(d.is_leaf)

True
False
True
True


In [ ]:
x = torch.ones(2, 2, requires_grad = False)
y = x + 2
z = y * y * 3
out = z.mean()

# x.retain_grad()

# y.retain_grad()
# z.retain_grad()

out.backward()

print(x.is_leaf)
print(y.is_leaf)
print(z.is_leaf)

print(x.grad)
print(y.grad)
print(z.grad)

RuntimeError: can't retain_grad on Tensor that has requires_grad=False

In [ ]:
# activation functions

torch.relu()
torch.sigmoid()
torch.tanh()

torch.nn.ReLU
torch.nn.Sigmoid
torch.nn.Tanh
torch.nn.Softmax
torch.nn.LeakyReLU
torch.nn.ELU

torch.nn.functional.relu()
torch.nn.functional.sigmoid()
......






In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

x = torch.tensor([-2, -1, 0, 1, 2])
print(torch.relu(x))

obj = nn.ReLU()
print(obj(x))

print(torch.nn.functional.relu(x))



tensor([0, 0, 0, 1, 2])
tensor([0, 0, 0, 1, 2])
tensor([0, 0, 0, 1, 2])


In [ ]:
# Loss fucntion


# nn.MSELoss()
# nn.CrossEntropyLoss()
# nn.BCELoss()

y_pred = torch.tensor([1.0, 2, 3, 4])
y_true = torch.tensor([1.0, 0, 3, 4])

mse = nn.MSELoss()
loss = mse(y_pred, y_true)
loss



tensor(1.)