In [ ]:
import torch.optim as optim

In [ ]:
# SGD
# optimizer = optim.SGD(p, lr = 0.01)

In [ ]:
# optimizer = optim.AdaGrad(p, lr = 0.01)

In [ ]:
# optimizer = optim.RMSprop(p, lr = 0.01, alpha = 0.99)


In [ ]:
# optimizer = optim.Adam(p, lr = 0.01)

# ANN

In [ ]:
import torch
import torch.nn as nn

layer1 = nn.Linear(in_features = 3, out_features = 2)

in1 = torch.tensor([1.0, 2.0, 3.0])

out1 = layer1(in1)

print(out1)


tensor([-1.2391, -1.2342], grad_fn=<ViewBackward0>)


In [ ]:
layer1.weight

Parameter containing:
tensor([[-0.0836,  0.3496, -0.5269],
        [ 0.0593, -0.0011, -0.3120]], requires_grad=True)

In [ ]:
layer1.bias

Parameter containing:
tensor([-0.2740, -0.3554], requires_grad=True)

In [ ]:
type(layer1.weight)

torch.nn.parameter.Parameter

In [ ]:
layer1.weight.data

tensor([[-0.0836,  0.3496, -0.5269],
        [ 0.0593, -0.0011, -0.3120]])

In [ ]:
new_weights = torch.tensor([[0.5, -0.5, 1.0],[1.5,-1.5, 0.0]])
new_bias = torch.tensor([0.1, -0.1])

layer1.weight.data = new_weights
layer1.bias.data = new_bias

In [ ]:
out1 = layer1(in1)
out1

tensor([ 2.6000, -1.6000], grad_fn=<ViewBackward0>)

In [ ]:
new_weights.requires_grad

False

In [ ]:
layer1.weight.requires_grad

True

In [ ]:
batch_input = torch.tensor([[1.0, 2, 3], [3.0, 5, 6], [7.0, 8, 9], [7.0, 8, 9]])

batch_output = layer1(batch_input)

print(batch_output)

tensor([[ 2.6000, -1.6000],
        [ 5.1000, -3.1000],
        [ 8.6000, -1.6000],
        [ 8.6000, -1.6000]], grad_fn=<AddmmBackward0>)


## nn.Module

In [ ]:
class LinearRegressionModel(nn.Module):
  def __init__(self):
    super(LinearRegressionModel, self).__init__()
    self.layer1 = nn.Linear(in_features = 1, out_features = 1)

  def forward(self, x):
    return self.layer1(x)

model = LinearRegressionModel()

In [ ]:
X = torch.linspace(0, 10, 15).reshape(-1, 1)
pred = model(X)
pred

tensor([[-0.5933],
        [-0.2902],
        [ 0.0129],
        [ 0.3159],
        [ 0.6190],
        [ 0.9221],
        [ 1.2251],
        [ 1.5282],
        [ 1.8313],
        [ 2.1343],
        [ 2.4374],
        [ 2.7405],
        [ 3.0435],
        [ 3.3466],
        [ 3.6497]], grad_fn=<AddmmBackward0>)

In [ ]:
model.layer1.weight

Parameter containing:
tensor([[0.4243]], requires_grad=True)

In [ ]:
model.layer1.bias

Parameter containing:
tensor([-0.5933], requires_grad=True)

In [ ]:
class SimpleModel(nn.Module):
  def __init__(self):
    super(SimpleModel, self).__init__()
    self.layer1 = nn.Linear(10, 5)
    self.relu = nn.ReLU()
    self.layer2 = nn.Linear(5, 1)

  def forward(self, x):
    x = self.layer1(x)
    x = self.relu(x)
    x = self.layer2(x)
    return x

In [ ]:
net = SimpleModel()
net

SimpleModel(
  (layer1): Linear(in_features=10, out_features=5, bias=True)
  (relu): ReLU()
  (layer2): Linear(in_features=5, out_features=1, bias=True)
)

In [ ]:
input = torch.randn(1, 10)
print(input)
output = net(input)
output

tensor([[-0.9212,  0.7840,  0.1168,  0.9789, -0.6890, -2.4142,  1.3393, -0.2858,
         -1.0372, -0.1790]])


tensor([[-0.4047]], grad_fn=<AddmmBackward0>)

In [ ]:
print(net.layer1.weight)
print(net.layer1.bias)
print(net.layer2.weight)
print(net.layer2.bias)

Parameter containing:
tensor([[-0.0684, -0.1490, -0.1617,  0.1615, -0.0910,  0.1363,  0.1601,  0.0893,
         -0.2833,  0.0531],
        [ 0.2758,  0.0334, -0.3135,  0.0941, -0.1075, -0.2655,  0.0106, -0.0625,
         -0.2395,  0.2669],
        [ 0.2843, -0.2787,  0.0680,  0.0330,  0.2919, -0.2383,  0.1887, -0.2199,
          0.2991,  0.0935],
        [ 0.2149, -0.1516, -0.2607,  0.0904,  0.3111,  0.2334, -0.2586,  0.1078,
         -0.2792,  0.0808],
        [-0.3136,  0.2365,  0.0366,  0.1578, -0.1888, -0.2501,  0.0408, -0.2580,
          0.1369, -0.0643]], requires_grad=True)
Parameter containing:
tensor([-0.3156,  0.2192,  0.0731,  0.1478, -0.1398], requires_grad=True)
Parameter containing:
tensor([[-0.0967, -0.1836, -0.2814,  0.1322, -0.0049]], requires_grad=True)
Parameter containing:
tensor([-0.2160], requires_grad=True)


In [ ]:
net.parameters()

<generator object Module.parameters at 0x78b3aa5c83c0>

In [ ]:
for each in net.parameters():
  print(each)

Parameter containing:
tensor([[-0.0684, -0.1490, -0.1617,  0.1615, -0.0910,  0.1363,  0.1601,  0.0893,
         -0.2833,  0.0531],
        [ 0.2758,  0.0334, -0.3135,  0.0941, -0.1075, -0.2655,  0.0106, -0.0625,
         -0.2395,  0.2669],
        [ 0.2843, -0.2787,  0.0680,  0.0330,  0.2919, -0.2383,  0.1887, -0.2199,
          0.2991,  0.0935],
        [ 0.2149, -0.1516, -0.2607,  0.0904,  0.3111,  0.2334, -0.2586,  0.1078,
         -0.2792,  0.0808],
        [-0.3136,  0.2365,  0.0366,  0.1578, -0.1888, -0.2501,  0.0408, -0.2580,
          0.1369, -0.0643]], requires_grad=True)
Parameter containing:
tensor([-0.3156,  0.2192,  0.0731,  0.1478, -0.1398], requires_grad=True)
Parameter containing:
tensor([[-0.0967, -0.1836, -0.2814,  0.1322, -0.0049]], requires_grad=True)
Parameter containing:
tensor([-0.2160], requires_grad=True)


In [ ]:
for each in net.parameters():
  print(each.shape)

torch.Size([5, 10])
torch.Size([5])
torch.Size([1, 5])
torch.Size([1])


# nn.Sequential

In [ ]:
model = nn.Sequential(
    nn.Linear(10, 5),
    nn.ReLU(),
    nn.Linear(5, 1))

print(model)

Sequential(
  (0): Linear(in_features=10, out_features=5, bias=True)
  (1): ReLU()
  (2): Linear(in_features=5, out_features=1, bias=True)
)


In [ ]:
input = torch.randn(1, 10)
model(input)

tensor([[0.1119]], grad_fn=<AddmmBackward0>)

In [ ]:
model[0].weight

Parameter containing:
tensor([[-0.0075, -0.0158, -0.1553, -0.0156, -0.0409, -0.0563, -0.1461,  0.2849,
         -0.2431, -0.2532],
        [-0.2584,  0.2925,  0.0079, -0.2796, -0.1661,  0.2149, -0.0012,  0.0966,
          0.1658,  0.2926],
        [-0.0022,  0.2786, -0.2931,  0.2332, -0.0801, -0.1135,  0.3143, -0.2097,
         -0.2325, -0.2014],
        [-0.0043,  0.0485,  0.3028,  0.0354, -0.0871,  0.0526,  0.1942,  0.0009,
          0.2455,  0.3099],
        [ 0.0828, -0.2684,  0.1244,  0.0329,  0.0430, -0.0337, -0.1285,  0.2087,
         -0.0480, -0.0479]], requires_grad=True)

In [ ]:
model[0].bias

Parameter containing:
tensor([0.1456, 0.2513, 0.1404, 0.1373, 0.2302], requires_grad=True)

In [ ]:
model[2].weight

Parameter containing:
tensor([[-0.3510,  0.1175,  0.3746, -0.3800,  0.0379]], requires_grad=True)

# Optimization

In [ ]:
class SimpleModel(nn.Module):
  def __init__(self):
    super(SimpleModel, self).__init__()
    self.layer1 = nn.Linear(10, 5)
    self.relu = nn.ReLU()
    self.layer2 = nn.Linear(5, 1)

  def forward(self, x):
    x = self.layer1(x)
    x = self.relu(x)
    x = self.layer2(x)
    return x

net = SimpleModel()
# net.parameters()


inputs = torch.randn(100, 10)
targets = torch.randn(100, 1)

criterion = nn.MSELoss()

optimizer = optim.SGD(net.parameters(), lr = 0.01)

for epoch in range(1000):
  optimizer.zero_grad()

  # forward pass
  outputs = net(inputs)

  # loss computation
  loss = criterion(outputs, targets)

  # backward pass
  loss.backward()
  optimizer.step()

  if epoch % 100 == 0:
    print('Epoch', epoch, 'Loss', loss.item())






Epoch 0 Loss 1.2540632486343384
Epoch 100 Loss 1.0855813026428223
Epoch 200 Loss 1.054436206817627
Epoch 300 Loss 1.0190913677215576
Epoch 400 Loss 0.9792024493217468
Epoch 500 Loss 0.9391087293624878
Epoch 600 Loss 0.9043773412704468
Epoch 700 Loss 0.8706095218658447
Epoch 800 Loss 0.8427315354347229
Epoch 900 Loss 0.8173635005950928


In [ ]:
torch.save(net, 'model.pt')

# ANN Full Example

In [ ]:
import numpy as np
X = np.random.rand(100, 1)*10
true_w = 3
true_b = 2
y = true_w*X + true_b + np.random.randn(100, 1)*0.2

# y

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 24)

In [ ]:
X_train_t = torch.tensor(X_train, dtype = torch.float32)
y_train_t = torch.tensor(y_train, dtype = torch.float32)
X_test_t = torch.tensor(X_test, dtype = torch.float32)
y_test_t = torch.tensor(y_test, dtype = torch.float32)


In [ ]:
class LinearReg(nn.Module):
  def __init__(self):
    super(LinearReg, self).__init__()
    self.linear = nn.Linear(1, 1)

  def forward(self, x):
    return self.linear(x)

model = LinearReg()

In [ ]:
model.linear.weight.item()

-0.5523146390914917

In [ ]:
model.linear.bias.item()

0.18448173999786377

In [ ]:
for each in model.parameters():
  print(each)

Parameter containing:
tensor([[-0.5523]], requires_grad=True)
Parameter containing:
tensor([0.1845], requires_grad=True)


In [ ]:
criterion = nn.MSELoss()

optimizer = optim.SGD(model.parameters(), lr = 0.01)

for epoch in range(1000):
  optimizer.zero_grad()
  outputs = model(X_train_t)
  loss = criterion(outputs, y_train_t)
  loss.backward()
  optimizer.step()

  if (epoch+1) % 100 == 0:
    print('Epoch:', epoch, 'Loss:', loss.item())
    print(model.linear.weight.item(), model.linear.bias.item())


Epoch: 99 Loss: 0.17627473175525665
3.1167120933532715 1.2001125812530518
Epoch: 199 Loss: 0.08964947611093521
3.074207067489624 1.4875314235687256
Epoch: 299 Loss: 0.05625467374920845
3.047816038131714 1.6659880876541138
Epoch: 399 Loss: 0.043380677700042725
3.0314297676086426 1.776790738105774
Epoch: 499 Loss: 0.0384175106883049
3.0212557315826416 1.8455877304077148
Epoch: 599 Loss: 0.036504246294498444
3.0149388313293457 1.8883029222488403
Epoch: 699 Loss: 0.035766635090112686
3.011016607284546 1.9148246049880981
Epoch: 799 Loss: 0.03548230975866318
3.0085811614990234 1.9312920570373535
Epoch: 899 Loss: 0.035372696816921234
3.0070693492889404 1.9415165185928345
Epoch: 999 Loss: 0.03533041477203369
3.0061304569244385 1.9478650093078613


In [ ]:
with torch.no_grad():
  preds = model(X_test_t)
  test_loss = criterion(preds, y_test_t)

print(test_loss)

tensor(0.0403)


In [ ]:
print(model.linear.weight.item())
print(model.linear.bias.item())

3.0061304569244385
1.9478650093078613


# Real world data ANN

In [ ]:
from sklearn.datasets import fetch_california_housing

data = fetch_california_housing()

In [ ]:
data.data

array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]])

In [ ]:
data.target

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])